# Generated by Django 5.0a1 on 2025-11-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrativo'), ('DOCENTE', 'Docente'), ('ALUMNO', 'Alumno')], default='ALUMNO', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dni', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='AlumnoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado_inscripcion', models.CharField(default='Activo', max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.alumno')),
            ],
            options={
                'db_table': 'alumno_materia',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('legajo', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tardanza', 'Tardanza'), ('Justificado', 'Justificado')], max_length=20)),
                ('justificativo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('validado_fecha', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.alumnomateria')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencias.docente')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.carrera')),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.materia'),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.IntegerField(help_text='AAAAMM, ej: 202401', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'periodo',
                'indexes': [models.Index(fields=['activo'], name='idx_periodo_activo')],
            },
        ),
        migrations.CreateModel(
            name='DocenteMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.periodo')),
            ],
            options={
                'db_table': 'docente_materia',
            },
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.periodo'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='idx_users_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['dni'], name='idx_alumno_dni'),
        ),
        migrations.AddIndex(
            model_name='docente',
            index=models.Index(fields=['legajo'], name='idx_docente_legajo'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='idx_asistencia_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['alumno_materia'], name='idx_asistencia_alumno_materia'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('alumno_materia', 'fecha'), name='unique_asistencia_fecha'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('codigo', 'carrera'), name='unique_materia_carrera'),
        ),
        migrations.AddIndex(
            model_name='docentemateria',
            index=models.Index(fields=['periodo'], name='idx_docente_materia_periodo'),
        ),
        migrations.AddConstraint(
            model_name='docentemateria',
            constraint=models.UniqueConstraint(fields=('docente', 'materia', 'periodo'), name='unique_docente_materia_periodo'),
        ),
        migrations.AddIndex(
            model_name='alumnomateria',
            index=models.Index(fields=['alumno'], name='idx_alumno_materia_alumno'),
        ),
        migrations.AddConstraint(
            model_name='alumnomateria',
            constraint=models.UniqueConstraint(fields=('alumno', 'materia', 'periodo'), name='unique_alumno_materia_periodo'),
        ),
    ]
